#!/bin/bash

# This script installs all listed APT packages
set -e

echo 'Installing packages...'
sudo apt update && sudo apt install -y \
apt-transport-https \
autoconf \
automake \
autotools-dev \
base-passwd \
bc \
bison \
bsdutils \
btop \
build-essential \
ca-certificates \
clang-format \
clangd \
cmake \
cryptsetup \
cryptsetup-bin \
cryptsetup-initramfs \
curl \
dash \
diffutils \
dmeventd \
efibootmgr \
emacs \
falcon-sensor \
findutils \
flex \
fonts-indic \
gawk \
gcc-riscv64-unknown-elf \
git \
git-email \
gnome-user-docs-fr \
gnupg \
gperf \
grep \
grub-common \
grub-efi-amd64-bin \
grub-efi-amd64-signed \
grub-gfxpayload-lists \
grub-pc \
grub-pc-bin \
grub2-common \
gzip \
hostname \
htop \
hunspell-en-au \
hunspell-en-ca \
hunspell-en-gb \
hunspell-en-za \
hunspell-fr \
hyphen-en-ca \
hyphen-en-gb \
hyphen-en-us \
hyphen-fr \
imwheel \
indent \
init \
kitty \
language-pack-en \
language-pack-en-base \
language-pack-fr \
language-pack-fr-base \
language-pack-gnome-en \
language-pack-gnome-en-base \
language-pack-gnome-fr \
language-pack-gnome-fr-base \
libaio-dev \
libaio1 \
libbluetooth-dev \
libbrlapi-dev \
libbz2-dev \
libcap-ng-dev \
libcapstone-dev \
libcurl4-gnutls-dev \
libdebconfclient0 \
libdevmapper-event1.02.1 \
libexpat1-dev \
libfdt-dev \
libflashrom1 \
libftdi1-2 \
libglib2.0-dev \
libgmp-dev \
libgtk-3-dev \
libibverbs-dev \
libiscsi-dev \
libjpeg8-dev \
libllvm13 \
liblvm2cmd2.03 \
liblzo2-dev \
libmpc-dev \
libmpfr-dev \
libncurses5-dev \
libnfs-dev \
libnuma-dev \
libpixman-1-dev \
librbd-dev \
librdmacm-dev \
libreoffice-help-common \
libreoffice-help-en-gb \
libreoffice-help-en-us \
libreoffice-help-fr \
libreoffice-l10n-en-gb \
libreoffice-l10n-en-za \
libreoffice-l10n-fr \
libsasl2-dev \
libsdl2-dev \
libseccomp-dev \
libslirp-dev \
libsnappy-dev \
libssh-dev \
libtool \
libvde-dev \
libvdeplug-dev \
libvte-2.91-dev \
libxen-dev \
linux-generic-hwe-22.04 \
login \
lvm2 \
meld \
mokutil \
mythes-en-au \
mythes-en-us \
mythes-fr \
ncurses-base \
ncurses-bin \
neovim \
ninja-build \
nodejs \
okular \
opam \
openssh-server \
os-prober \
patchutils \
python-tk \
python3 \
python3-dev \
python3-pip \
python3-tk \
pythonpy \
ripgrep \
rocketchat \
shim-signed \
snapd \
texinfo \
thin-provisioning-tools \
thunderbird-locale-en \
thunderbird-locale-en-gb \
thunderbird-locale-en-us \
thunderbird-locale-fr \
tmux \
ubuntu-desktop \
ubuntu-desktop-minimal \
ubuntu-minimal \
ubuntu-restricted-addons \
ubuntu-standard \
ubuntu-wallpapers \
valgrind \
vim \
xclip \
xfslibs-dev \
zlib1g-dev \
zsh 

