name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  commit_lint:
    runs-on: ubuntu-latest
    steps:
      # Check commit messages
      - uses: webiny/action-conventional-commits@v1.1.0

  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        neovim_version:
          - 'v0.9.5'
          # - 'v0.10.0'

    env:
      NEOVIM_VERSION: ${{ matrix.neovim_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1.5"

      - uses: leafo/gh-actions-luarocks@v4

      - uses: tree-sitter/setup-action/cli@v1

      - name: Download nvim-test
        run: make nvim-test

      - name: Download nvim-treesitter
        run: make nvim-treesitter

      - name: Parsers Cache
        uses: actions/cache@v4
        with:
          path: ./nvim-treesitter/parser/
          key: parsers-${{ join(matrix.*, '-') }}-${{ hashFiles(
            './nvim-treesitter/lockfile.json',
            './nvim-treesitter/lua/nvim-treesitter/install.lua',
            './nvim-treesitter/lua/nvim-treesitter/parsers.lua') }}

      - name: Install parsers
        run: make parsers

      - name: Run Test
        run: make test
